#%RAML 1.0 Library
usage:
traits:
  destinationLocation: !include /libraries/schedules/traits/queryparams-destinationLocation-trait.raml
  departureLocation: !include /libraries/schedules/traits/queryparams-departureLocation-trait.raml